package br.com.lucashilles.view;

import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author "Lucas HS"
 */
public class DadosVertice extends javax.swing.JPanel {

    /**
     * Creates new form DadosVertice
     */
    public DadosVertice() {
        initComponents();
    }

    public JButton getjBtnAceitar() {
        return jBtnAceitar;
    }

    public JTextField getjTFX() {
        return jTFX;
    }

    public JTextField getjTFY() {
        return jTFY;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jTFX = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTFY = new javax.swing.JTextField();
        jBtnAceitar = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("X (cm) :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        add(jLabel1, gridBagConstraints);

        jTFX.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTFX.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTFX.setText("0.0");
        jTFX.setPreferredSize(new java.awt.Dimension(75, 23));
        jTFX.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTFFocusGained(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 0);
        add(jTFX, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Y (cm) :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        add(jLabel2, gridBagConstraints);

        jTFY.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTFY.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTFY.setText("0.0");
        jTFY.setPreferredSize(new java.awt.Dimension(75, 23));
        jTFY.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTFFocusGained(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 0);
        add(jTFY, gridBagConstraints);

        jBtnAceitar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jBtnAceitar.setText("Aceitar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(jBtnAceitar, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jTFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFFocusGained
        if (!(evt.getSource() instanceof JTextField)) {
            return;
        }
        JTextField txt = (JTextField) evt.getSource();
        txt.selectAll();
    }//GEN-LAST:event_jTFFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAceitar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTFX;
    private javax.swing.JTextField jTFY;
    // End of variables declaration//GEN-END:variables
}
