package br.com.lucashilles.view;

import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;

/**
 *
 * @author "Lucas HS"
 */
public class JanelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JanelaPrincipal
     */
    public JanelaPrincipal() {
        initComponents();
        jLListaDeVertices.setModel(new DefaultListModel());

        DefaultListCellRenderer renderer = (DefaultListCellRenderer) jLListaDeVertices.getCellRenderer();
        renderer.setHorizontalAlignment(JLabel.CENTER);

        //setVisible(true);
    }

    public JButton getjBtnAceitar() {
        return jBtnAceitar;
    }

    public JButton getjBtnAdicionar() {
        return jBtnAdicionar;
    }

    public JButton getjBtnLimpar() {
        return jBtnLimpar;
    }

    public JButton getjBtnRemover() {
        return jBtnRemover;
    }

    public JList<String> getjLListaDeVertices() {
        return jLListaDeVertices;
    }

    public JPanel getjPQuadro() {
        return jPQuadro;
    }

    public JLabel getjLInfo() {
        return jLInfo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jLListaDeVertices = new javax.swing.JList<>();
        jBtnAdicionar = new javax.swing.JButton();
        jBtnRemover = new javax.swing.JButton();
        jPQuadro = new javax.swing.JPanel();
        jBtnAceitar = new javax.swing.JButton();
        jBtnLimpar = new javax.swing.JButton();
        jLInfo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Configurar Seção");

        jLListaDeVertices.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLListaDeVertices.setPreferredSize(new java.awt.Dimension(105, 95));
        jScrollPane2.setViewportView(jLListaDeVertices);

        jBtnAdicionar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jBtnAdicionar.setText("+");

        jBtnRemover.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jBtnRemover.setText("-");

        jPQuadro.setBorder(javax.swing.BorderFactory.createTitledBorder("Seção"));
        jPQuadro.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPQuadroLayout = new javax.swing.GroupLayout(jPQuadro);
        jPQuadro.setLayout(jPQuadroLayout);
        jPQuadroLayout.setHorizontalGroup(
            jPQuadroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 323, Short.MAX_VALUE)
        );
        jPQuadroLayout.setVerticalGroup(
            jPQuadroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jBtnAceitar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jBtnAceitar.setText("Aceitar");

        jBtnLimpar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jBtnLimpar.setText("Limpar");

        jLInfo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLInfo.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnRemover, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                        .addGap(6, 6, 6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                        .addGap(1, 1, 1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPQuadro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnAceitar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnLimpar)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBtnAceitar, jBtnLimpar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPQuadro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnAdicionar)
                    .addComponent(jBtnRemover)
                    .addComponent(jBtnAceitar)
                    .addComponent(jBtnLimpar)
                    .addComponent(jLInfo))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAceitar;
    private javax.swing.JButton jBtnAdicionar;
    private javax.swing.JButton jBtnLimpar;
    private javax.swing.JButton jBtnRemover;
    private javax.swing.JLabel jLInfo;
    private javax.swing.JList<String> jLListaDeVertices;
    private javax.swing.JPanel jPQuadro;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
